version: "3.3"

services:
  lawconnect-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lawconnect-backend
    ports:
      - "8085:8080"   # maps host 8085 -> container 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/springdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""     # ✅ empty password
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: -Xms512m -Xmx1024m
    extra_hosts:
      - "host.docker.internal:192.168.56.10"  # <-- your Vagrant host IP
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - lawconnect-network

  mysql:
    image: mysql:8.0
    container_name: lawconnect-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # ✅ enable empty password mode
      MYSQL_DATABASE: springdb            # optional, creates DB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lawconnect-network
    restart: on-failure

volumes:
  mysql_data:
    driver: local

networks:
  lawconnect-network:
    driver: bridge
